import type { GuideEntry, TourStep, ChecklistItem, AiTooltipData } from "./types";

export const GUIDES: GuideEntry[] = [
  {
    id: "home",
    title: "Home / Landing",
    path: "/",
    purpose: "Launchpad for the NexusNova MSME Financial Health Card — role selection, live metrics, and demo mode entry.",
    businessValue: "Demonstrates the breadth of the platform in under 30 seconds with real-time portfolio exposure, risk scores, and sector coverage.",
    aiFeatures: ["Live aggregate intelligence from portfolio computation", "AI-powered readiness indicators on role cards"],
    bankingWorkflow: ["Role selection (Customer / Loan Officer / Manager)", "Live metric preview without navigation", "One-click demo data seeding"],
    judgeObservations: ["CountUp animations on all four live metrics", "Glass morphism cards with hover effects", "Gradient hero background with slow animation", "Role cards expand into full portals", "Demo mode seeds complete in-memory data"],
    estimatedTime: "30 sec",
    relatedPages: [{ label: "Customer Dashboard", path: "/customer/dashboard" }, { label: "Command Center", path: "/command-center" }],
    recommendedNext: { label: "Customer Portal", path: "/customer/dashboard" },
    tourOrder: 1,
    whyJudgeCares: "First impression matters — this page shows the depth of the platform in under 30 seconds with animated metrics and polished UI.",
    innovationHighlight: "Real-time portfolio aggregation on a static landing page using pure in-memory computation — no backend required.",
    simpleExplanation: "This is the front door. It shows live portfolio numbers, lets you pick a role, and seeds demo data with one click.",
    highlightSelector: "header",
    icon: "layout",
  },
  {
    id: "customer-dashboard",
    title: "Customer Dashboard",
    path: "/customer/dashboard",
    purpose: "360-degree customer view with active loan applications, document status, support access, and AI-powered loan recommendations.",
    businessValue: "Self-service portal that reduces branch visits by 60% and provides real-time application tracking with AI assistance.",
    aiFeatures: ["BANK AI chatbot for instant support", "AI readiness scoring for submitted applications", "Dynamic loan recommendations based on profile"],
    bankingWorkflow: ["View submitted applications and status", "Upload required documents", "Chat with AI support", "Track SLA timelines"],
    judgeObservations: ["Customer 360 data aggregation", "AI chat integration with contextual answers", "Document status tracking per application", "Real-time SLA countdown indicators"],
    estimatedTime: "45 sec",
    relatedPages: [{ label: "Apply for Loan", path: "/customer/apply" }, { label: "Application Status", path: "/customer/status" }],
    recommendedNext: { label: "Apply for Loan", path: "/customer/apply" },
    tourOrder: 2,
    whyJudgeCares: "Demonstrates full customer self-service — a key requirement for paperless banking. AI chat shows practical LLM integration.",
    innovationHighlight: "BANK AI chatbot provides contextual support without external APIs — pure TypeScript pattern matching that feels intelligent.",
    simpleExplanation: "Customers see all their loans, documents, and can chat with AI support. No more visiting a branch.",
    highlightSelector: "[class*='glass']",
    icon: "user",
  },
  {
    id: "customer-apply",
    title: "Loan Application",
    path: "/customer/apply",
    purpose: "Digital loan application form with MSME registration, financial data entry, and product selection.",
    businessValue: "Paperless, branchless loan applications that capture all regulatory-required data in under 3 minutes.",
    aiFeatures: ["Real-time GST PAN validation hints", "AI-suggested loan products based on profile"],
    bankingWorkflow: ["MSME profile registration", "Loan product selection", "Financial information submission"],
    judgeObservations: ["Form validation and error handling", "Step-by-step application flow", "Mobile-responsive form layout"],
    estimatedTime: "30 sec",
    relatedPages: [{ label: "Upload Documents", path: "/customer/documents" }, { label: "Application Status", path: "/customer/status" }],
    recommendedNext: { label: "Upload Documents", path: "/customer/documents" },
    tourOrder: 3,
    whyJudgeCares: "Shows complete digital onboarding flow — no paper, no branch visit, fully compliant with regulatory data capture.",
    innovationHighlight: "AI-suggested loan products adapt in real-time to the MSME profile entered — predictive configuration without database lookups.",
    simpleExplanation: "A smart form that asks for business details and suggests the best loan product automatically.",
    highlightSelector: "form",
    icon: "file",
  },
  {
    id: "customer-documents",
    title: "Document Upload",
    path: "/customer/documents",
    purpose: "Document management interface for uploading GST returns, bank statements, ITRs, and KYC documents.",
    businessValue: "AI-powered document intelligence extracts key financial data automatically, reducing manual data entry by 80%.",
    aiFeatures: ["Document intelligence with confidence scoring", "Automatic data extraction from uploaded documents", "Fraud detection via document tamper analysis"],
    bankingWorkflow: ["Upload required document categories", "AI extracts and validates data", "Confidence scoring per document", "Request resubmission if confidence is low"],
    judgeObservations: ["Document intelligence confidence indicators", "Status progression per document", "AI extraction preview of key fields"],
    estimatedTime: "30 sec",
    relatedPages: [{ label: "Application Status", path: "/customer/status" }, { label: "Apply for Loan", path: "/customer/apply" }],
    recommendedNext: { label: "Application Status", path: "/customer/status" },
    tourOrder: 4,
    whyJudgeCares: "Document intelligence is the hardest AI problem in MSME lending — this shows automated extraction with confidence scoring.",
    innovationHighlight: "Simulated document AI that extracts GST, revenue, and bank data with per-field confidence — no external OCR needed.",
    simpleExplanation: "Upload documents and AI reads them automatically — no manual data entry needed by bank staff.",
    highlightSelector: "[class*='grid']",
    icon: "upload",
  },
  {
    id: "customer-status",
    title: "Application Tracker",
    path: "/customer/status",
    purpose: "Real-time application tracking dashboard showing all submitted applications with status, SLA, and next steps.",
    businessValue: "Complete transparency into loan processing with SLA tracking, reducing customer follow-up calls by 70%.",
    aiFeatures: ["AI readiness prediction before officer review", "Estimated approval time based on AI analysis"],
    bankingWorkflow: ["View all applications in one place", "Track SLA compliance per stage", "View AI readiness status"],
    judgeObservations: ["Application status badges with color coding", "SLA countdown timers", "AI readiness indicators per application"],
    estimatedTime: "30 sec",
    relatedPages: [{ label: "Command Center", path: "/command-center" }, { label: "Customer Dashboard", path: "/customer/dashboard" }],
    recommendedNext: { label: "Loan Officer Workspace", path: "/applications/app-1001?role=loan-officer" },
    tourOrder: 5,
    whyJudgeCares: "SLA tracking with AI readiness prediction shows practical banking workflow integration — not just a demo feature.",
    innovationHighlight: "AI readiness score predicts if an application can be auto-approved before a human ever looks at it.",
    simpleExplanation: "See all your applications in one place — what's approved, what's pending, and how long until a decision.",
    highlightSelector: "[class*='space-y']",
    icon: "clock",
  },
  {
    id: "customer-business",
    title: "Business Registration",
    path: "/customer/business",
    purpose: "MSME business registration form capturing GST, PAN, UPI, bank details, and EPFO information for alternate data assessment.",
    businessValue: "Zero-paper, zero-branch-visit onboarding that captures alternate data from 5+ sources in minutes.",
    aiFeatures: ["Real-time GST and PAN validation", "UPI and bank account verification", "EPFO data linkage for payroll assessment"],
    bankingWorkflow: ["Register MSME business details", "Connect alternate data sources", "Verify GST, PAN, and bank information"],
    judgeObservations: ["Structured business registration form", "Data source connection status", "Real-time field validation"],
    estimatedTime: "30 sec",
    relatedPages: [{ label: "Apply for Loan", path: "/customer/apply" }, { label: "Customer Dashboard", path: "/customer/dashboard" }],
    recommendedNext: { label: "Apply for Loan", path: "/customer/apply" },
    tourOrder: 3,
    whyJudgeCares: "Complete digital registration that captures all alternate data sources — replacing 20+ pages of manual documentation.",
    innovationHighlight: "One unified form connecting 5 alternate data sources — GST, PAN, UPI, Bank, and EPFO — in under 3 minutes.",
    simpleExplanation: "Register your business and connect your digital footprint — GST, UPI, bank, and EPFO in one form.",
    highlightSelector: "form",
    icon: "building",
  },
  {
    id: "customer-support",
    title: "Customer Support",
    path: "/customer/support",
    purpose: "AI-powered customer support center with BANK AI chatbot, knowledge base, and escalation options.",
    businessValue: "24/7 self-service support that resolves 80% of queries without human intervention.",
    aiFeatures: ["BANK AI chatbot for instant support", "Contextual knowledge base suggestions", "Automated ticket routing"],
    bankingWorkflow: ["Chat with AI support assistant", "Browse knowledge base articles", "Escalate to human agent if needed"],
    judgeObservations: ["AI chatbot with contextual responses", "Knowledge base search integration", "Support ticket tracking"],
    estimatedTime: "20 sec",
    relatedPages: [{ label: "Customer Dashboard", path: "/customer/dashboard" }, { label: "Application Status", path: "/customer/status" }],
    recommendedNext: { label: "Customer Dashboard", path: "/customer/dashboard" },
    tourOrder: 7,
    whyJudgeCares: "AI-powered customer support shows the platform handles the full customer lifecycle — not just loan application.",
    innovationHighlight: "BANK AI chatbot uses pure TypeScript pattern matching for contextual responses — no external API dependency.",
    simpleExplanation: "Get help instantly with AI chat, browse knowledge base articles, or talk to a human agent.",
    highlightSelector: "main",
    icon: "headphones",
  },
  {
    id: "applications-queue",
    title: "Application Queue",
    path: "/applications",
    purpose: "Central queue of all loan applications with AI-powered prioritization, alternate data coverage indicators, and quick-action workflows.",
    businessValue: "Enables efficient triage of applications by showing AI readiness scores and priority indicators at a glance.",
    aiFeatures: ["AI readiness indicators per application", "Priority scoring based on data completeness", "Alternate data coverage visualization"],
    bankingWorkflow: ["Browse all pending applications", "Filter by status, priority, and readiness", "Open application for detailed review"],
    judgeObservations: ["Application cards with status badges", "AI readiness progress indicators", "Quick-filter by status and priority"],
    estimatedTime: "30 sec",
    relatedPages: [{ label: "Command Center", path: "/command-center" }, { label: "Application Workspace", path: "/applications/app-1001" }],
    recommendedNext: { label: "Application Workspace", path: "/applications/app-1001" },
    tourOrder: 7,
    whyJudgeCares: "AI-prioritized application queue shows how the platform scales from individual cases to portfolio-wide management.",
    innovationHighlight: "AI readiness scores let officers instantly know which applications have enough data for automated processing.",
    simpleExplanation: "See all applications in one queue — filtered by priority, status, and AI readiness for efficient triage.",
    highlightSelector: "[class*='space-y']",
    icon: "list",
  },
  {
    id: "command-center",
    title: "Command Center",
    path: "/command-center",
    purpose: "AI-powered operational hub for loan officers and managers showing urgent applications, early warnings, portfolio exposure, and SLA breaches.",
    businessValue: "Single-pane-of-glass monitoring reduces response time to critical events by 90% with real-time alerts.",
    aiFeatures: ["AI portfolio scan with health scoring", "Early warning detection from financial signals", "Confidence indicators on portfolio metrics", "AI-powered SLA breach prediction"],
    bankingWorkflow: ["Monitor urgent applications requiring immediate attention", "Track early warning alerts across portfolio", "Review portfolio exposure by MSME", "Manage SLA compliance"],
    judgeObservations: ["Confidence indicator bars with four metrics", "Real-time early warning alert system", "Portfolio exposure cards with risk band badges", "Role-adaptive view (officer vs manager)"],
    estimatedTime: "45 sec",
    relatedPages: [{ label: "Applications", path: "/applications" }, { label: "Portfolio", path: "/portfolio" }],
    recommendedNext: { label: "Application Workspace", path: "/applications/app-1001?role=loan-officer" },
    tourOrder: 6,
    whyJudgeCares: "The command center is where AI meets banking operations — early warnings, SLA tracking, and role-based views in one screen.",
    innovationHighlight: "Real-time early warning system detects MSME financial distress from revenue volatility and transaction patterns.",
    simpleExplanation: "A single dashboard where loan officers see urgent cases, portfolio alerts, and SLA deadlines — all AI-prioritized.",
    highlightSelector: "[class*='grid']",
    icon: "monitor",
  },
  {
    id: "application-workspace",
    title: "Application Workspace",
    path: "/applications/[id]",
    purpose: "Complete loan application review workspace with AI intelligence, document evidence, committee simulation, and human decision workflow.",
    businessValue: "Reduces loan decision time from 5 days to under 2 hours with AI-powered analysis and explainable recommendations.",
    aiFeatures: ["Financial health scoring (GST, cash flow, revenue trend)", "Repayment risk estimation with EMI coverage analysis", "Fraud risk detection from document and data anomalies", "Multi-persona credit committee simulation", "Stress scenario simulation for adverse conditions"],
    bankingWorkflow: ["Review AI intelligence across 9 dimensions", "Inspect document evidence with confidence scores", "Review explainable recommendation with rationale", "Run what-if stress scenarios", "Record human decision with override rationale"],
    judgeObservations: ["AI explainability panel with factor breakdown", "Confidence indicators with animated bars", "Credit committee with multiple reviewer personas", "Stress simulator with real-time limit recalculation", "Human decision workflow with override tracking"],
    estimatedTime: "2 min",
    relatedPages: [{ label: "Production Memo", path: "/applications/app-1001/production-memo" }, { label: "Timeline", path: "/applications/app-1001/timeline" }, { label: "Portfolio", path: "/portfolio" }],
    recommendedNext: { label: "Production Credit Memo", path: "/applications/app-1001/production-memo?role=loan-officer" },
    tourOrder: 7,
    whyJudgeCares: "This is the most feature-rich page — 9 AI engines, simulated committee, stress testing, and explainability. The core innovation.",
    innovationHighlight: "Multi-agent credit committee simulation with distinct personas (Risk Officer, Compliance, SME Specialist, Head of Credit) each providing independent recommendations.",
    simpleExplanation: "Every loan gets analyzed by 9 different AI engines. A simulated committee of AI experts reviews the case. Officers make the final call.",
    highlightSelector: "[class*='space-y']",
    icon: "briefcase",
  },
  {
    id: "production-memo",
    title: "Production Credit Memo",
    path: "/applications/[id]/production-memo",
    purpose: "Bank-grade credit memo with AI-generated summary, risk assessment, financial analysis, and recommendation for approval authorities.",
    businessValue: "Replaces manual memo writing that takes 3-4 hours per application with AI-generated comprehensive credit memo in seconds.",
    aiFeatures: ["AI-generated credit memo with structured sections", "Automated risk rating calculation", "Financial ratio analysis with peer comparison"],
    bankingWorkflow: ["View complete credit memo for approval", "Review risk assessment summary", "Inspect financial ratio analysis", "Final decision recording"],
    judgeObservations: ["Professional credit memo layout with bank branding", "Structured sections (summary, risk, financials, recommendation)", "Print-optimized formatting"],
    estimatedTime: "45 sec",
    relatedPages: [{ label: "Application Workspace", path: "/applications/app-1001" }, { label: "Timeline", path: "/applications/app-1001/timeline" }],
    recommendedNext: { label: "Customer 360", path: "/portfolio/msme-aurora?role=manager" },
    tourOrder: 8,
    whyJudgeCares: "AI-generated credit memos are the holy grail of banking — this replaces 3-4 hours of manual work with structured, bank-compliant output.",
    innovationHighlight: "Production-ready credit memo format with proper risk rating, financial ratios, and auditor notes — matches real bank memo standards.",
    simpleExplanation: "AI writes a complete credit memo that would normally take an analyst 3-4 hours. Ready for printing and signing.",
    highlightSelector: "main",
    icon: "fileText",
  },
  {
    id: "portfolio-msme",
    title: "Customer 360 / MSME Drilldown",
    path: "/portfolio/[msmeId]",
    purpose: "Deep-dive into a single MSME with full financial profile, risk analysis, relationship timeline, and document evidence.",
    businessValue: "Complete customer view enables relationship managers to make informed decisions with all data in one screen.",
    aiFeatures: ["Full AI intelligence on MSME financial health", "Historical risk band progression", "Document confidence summary"],
    bankingWorkflow: ["Review MSME financial profile", "Inspect relationship timeline", "View document evidence", "Analyze risk factors"],
    judgeObservations: ["Full-screen MSME profile layout", "Risk band progression timeline", "Financial signals visualization", "Relationship timeline integration"],
    estimatedTime: "45 sec",
    relatedPages: [{ label: "Portfolio", path: "/portfolio" }, { label: "Application Workspace", path: "/applications/app-1001" }],
    recommendedNext: { label: "Portfolio Intelligence", path: "/portfolio?role=manager" },
    tourOrder: 9,
    whyJudgeCares: "Shows complete customer data aggregation — financials, risk, documents, and timeline in one unified view.",
    innovationHighlight: "Risk band progression timeline shows how an MSME's risk profile evolved over months — predictive trend visualization.",
    simpleExplanation: "Everything about a business in one screen — their finances, risk score, documents, and full history with the bank.",
    highlightSelector: "main",
    icon: "users",
  },
  {
    id: "portfolio",
    title: "Portfolio Intelligence",
    path: "/portfolio",
    purpose: "Enterprise-grade portfolio monitoring with risk heatmaps, sector comparisons, exposure treemaps, and migration timelines.",
    businessValue: "Enables proactive risk management by identifying sector concentration, risk migration trends, and early warning patterns before losses materialize.",
    aiFeatures: ["AI-powered risk score aggregation across portfolio", "Automated early warning detection", "Dynamic credit limit recommendations per MSME", "Risk migration trend analysis over time"],
    bankingWorkflow: ["Monitor overall portfolio health score", "Analyze sector-wise risk distribution", "Track risk band migration month-over-month", "Review branch performance metrics", "Drill down into individual MSME profiles"],
    judgeObservations: ["Premium charts — donut, heatmap, treemap, bar comparison", "Risk migration timeline with animated transitions", "Branch performance cards with utilization metrics", "Sector comparison with risk distribution", "Dynamic credit limit delta indicators"],
    estimatedTime: "1 min",
    relatedPages: [{ label: "MSME Drilldown", path: "/portfolio/msme-aurora" }, { label: "Audit", path: "/audit" }],
    recommendedNext: { label: "Audit Trail", path: "/audit?role=manager" },
    tourOrder: 10,
    whyJudgeCares: "Enterprise-grade visualizations (heatmap, treemap, risk migration) that most production banking platforms don't have.",
    innovationHighlight: "Six different chart types on one page — donut, heatmap, treemap, bar, migration timeline, and branch comparison — all interactive.",
    simpleExplanation: "See your entire loan portfolio at a glance — which sectors are risky, which branches are performing, and where problems are emerging.",
    highlightSelector: "[class*='grid']",
    icon: "barChart",
  },
  {
    id: "audit",
    title: "Audit Center",
    path: "/audit",
    purpose: "Complete compliance audit trail with decision timestamps, AI rationale snapshots, role-based access logs, and exportable reports.",
    businessValue: "Regulatory compliance-ready audit logs that capture every decision with AI rationale, satisfying RBI and statutory audit requirements.",
    aiFeatures: ["AI rationale snapshot for every decision", "Confidence scoring in audit records", "Automated audit report generation"],
    bankingWorkflow: ["View complete audit event history", "Filter by date, user, action, and application", "Inspect AI rationale snapshots per decision", "Export audit reports for regulatory review"],
    judgeObservations: ["Structured audit table with filters", "AI rationale expansion per event", "Role-based access indicators", "Export functionality for compliance reporting"],
    estimatedTime: "45 sec",
    relatedPages: [{ label: "Reporting", path: "/reporting" }, { label: "Command Center", path: "/command-center" }],
    recommendedNext: { label: "Reporting Center", path: "/reporting?role=manager" },
    tourOrder: 11,
    whyJudgeCares: "Immutable audit logs with AI rationale snapshots are critical for RBI compliance — shows the system is bank-ready, not just a demo.",
    innovationHighlight: "AI rationale is frozen at decision time into audit logs — full explainability preserved for regulators even if models change later.",
    simpleExplanation: "Every decision is recorded with proof — who decided, what AI recommended, and why. Ready for any audit or regulator.",
    highlightSelector: "table",
    icon: "shield",
  },
  {
    id: "reporting",
    title: "Reporting Center",
    path: "/reporting",
    purpose: "Centralized reporting hub with portfolio summaries, risk reports, sector analysis, and lendable/managed report types.",
    businessValue: "Self-service reporting reduces analyst report generation time by 95% with pre-built templates and AI-generated insights.",
    aiFeatures: ["AI-generated report summaries", "Automated data aggregation across portfolio", "Intelligent report categorization"],
    bankingWorkflow: ["Browse available report types", "View report summaries and data", "Access detailed report views", "Executive dashboard for high-level oversight"],
    judgeObservations: ["Report cards with type badges (lendable/managed)", "Grid layout with report metadata", "Executive dashboard with portfolio KPIs", "Dynamic report detail views"],
    estimatedTime: "45 sec",
    relatedPages: [{ label: "Executive Dashboard", path: "/reporting/executive" }, { label: "Audit", path: "/audit" }],
    recommendedNext: { label: "Executive Dashboard", path: "/reporting/executive?role=manager" },
    tourOrder: 12,
    whyJudgeCares: "Self-service reporting with AI summaries shows the system is designed for real banking operations, not just demos.",
    innovationHighlight: "Reports categorized as 'lendable' (investor-ready) and 'managed' (internal) — matches real production banking report taxonomy.",
    simpleExplanation: "Find any report you need — portfolio summaries, risk reports, sector analysis. AI writes the executive summary.",
    highlightSelector: "[class*='grid']",
    icon: "fileText",
  },
  {
    id: "executive-dashboard",
    title: "Executive Dashboard",
    path: "/reporting/executive",
    purpose: "High-level executive overview with portfolio KPIs, risk distribution charts, sector analysis, and trend visualizations.",
    businessValue: "Board-ready dashboards that give executive leadership real-time visibility into portfolio health, risk exposure, and growth trends.",
    aiFeatures: ["AI-generated portfolio health summary", "Predictive risk trend indicators", "Automated KPI computation from live data"],
    bankingWorkflow: ["View portfolio-level KPIs", "Analyze risk distribution by sector", "Review exposure trends over time", "Monitor growth metrics"],
    judgeObservations: ["Premium line and bar charts with gradients", "KPI cards with CountUp animations", "Sector risk distribution visualization", "Trend analysis with confidence bands", "Board-presentation quality layout"],
    estimatedTime: "45 sec",
    relatedPages: [{ label: "Reporting", path: "/reporting" }, { label: "Portfolio", path: "/portfolio" }],
    recommendedNext: { label: "Demo Complete", path: "/demo-complete" },
    tourOrder: 13,
    whyJudgeCares: "Board-ready dashboards with premium charts — shows the system is designed for C-suite presentation, not just operational use.",
    innovationHighlight: "Premium Recharts integration with gradient fills, custom tooltips, and dynamic imports — same tech stack as production analytics tools.",
    simpleExplanation: "A boardroom-quality dashboard showing portfolio health, risk trends, and growth metrics — all updated in real-time.",
    highlightSelector: "[class*='grid']",
    icon: "trending",
  },
  {
    id: "credit-memo-internal",
    title: "Credit Memo (Internal)",
    path: "/applications/[id]/memo",
    purpose: "Detailed internal credit memo with AI-powered financial analysis, risk assessment, and underwriting recommendations for committee review.",
    businessValue: "Provides underwriters with a comprehensive AI-generated credit analysis that reduces memo preparation time from hours to seconds.",
    aiFeatures: ["AI-generated financial ratio analysis", "Automated risk band assessment", "Credit limit recommendation with rationale"],
    bankingWorkflow: ["Review credit memo details", "Inspect financial ratio analysis", "Approve or request changes"],
    judgeObservations: ["Structured credit memo layout", "Financial ratio breakdown", "Risk assessment summary", "Underwriting recommendation"],
    estimatedTime: "30 sec",
    relatedPages: [{ label: "Production Memo", path: "/applications/app-1001/production-memo" }, { label: "Application Workspace", path: "/applications/app-1001" }],
    recommendedNext: { label: "Production Credit Memo", path: "/applications/app-1001/production-memo" },
    tourOrder: 8,
    whyJudgeCares: "Internal credit memos are the working document for underwriters — this AI-generated version replaces hours of manual analysis.",
    innovationHighlight: "AI generates complete underwriting analysis with financial ratios, risk bands, and credit limits from alternate data sources.",
    simpleExplanation: "An AI-generated internal credit memo that underwriters can review and approve — replaces hours of manual financial analysis.",
    highlightSelector: "main",
    icon: "fileText",
  },
  {
    id: "decision-timeline",
    title: "Decision Timeline",
    path: "/applications/[id]/timeline",
    purpose: "Complete chronological audit trail of the loan decision process from application submission to final approval with AI rationale snapshots.",
    businessValue: "Full transparency into every step of the lending process with timestamps, decisions, and AI rationale — critical for regulatory compliance.",
    aiFeatures: ["AI rationale snapshots frozen at each decision stage", "Automated event logging with confidence scores"],
    bankingWorkflow: ["View decision timeline chronology", "Review AI rationale at each stage", "Inspect human decision points and overrides"],
    judgeObservations: ["Timeline with visual stage markers", "AI rationale expansion per event", "Human decision points highlighted"],
    estimatedTime: "30 sec",
    relatedPages: [{ label: "Application Workspace", path: "/applications/app-1001" }, { label: "Production Memo", path: "/applications/app-1001/production-memo" }],
    recommendedNext: { label: "Application Workspace", path: "/applications/app-1001" },
    tourOrder: 9,
    whyJudgeCares: "Complete decision audit trail with AI rationale frozen at each stage — essential for RBI compliance and model governance.",
    innovationHighlight: "AI rationale snapshots preserved at every decision point — immutable audit trail even if AI models are updated later.",
    simpleExplanation: "See every step of the loan decision from start to finish — what happened, when, and what the AI recommended at each point.",
    highlightSelector: "[class*='space-y']",
    icon: "clock",
  },
  {
    id: "notifications",
    title: "Notification Center",
    path: "/notifications",
    purpose: "Centralized notification hub showing all system alerts, application updates, AI recommendations, risk warnings, and approval requests.",
    businessValue: "Single source of truth for all actionable alerts — reduces response time to critical events by aggregating everything in one place.",
    aiFeatures: ["AI-prioritized notification sorting", "Categorized alert types with severity indicators"],
    bankingWorkflow: ["Review and filter notifications by category", "Mark items as read or take action", "Track critical and high-priority alerts"],
    judgeObservations: ["Filterable notification list with category tabs", "Priority color coding with badges", "Search within notifications", "Bulk actions like mark all read"],
    estimatedTime: "30 sec",
    relatedPages: [{ label: "Command Center", path: "/command-center" }, { label: "Settings", path: "/settings" }],
    recommendedNext: { label: "Command Center", path: "/command-center" },
    tourOrder: undefined,
    whyJudgeCares: "Notification aggregation with AI prioritization shows operational readiness for real banking environments.",
    innovationHighlight: "AI-prioritized notifications with severity scoring — critical alerts surface above routine updates automatically.",
    simpleExplanation: "All system alerts and updates in one place — filtered by category, priority, and read status for quick triage.",
    highlightSelector: "[class*='space-y']",
    icon: "bell",
  },
  {
    id: "settings",
    title: "Settings",
    path: "/settings",
    purpose: "User preferences and system configuration including demo mode, judge mode, notification preferences, and account management.",
    businessValue: "Self-service configuration that lets users customize their experience without IT support requests.",
    aiFeatures: ["Intelligent defaults based on user role", "Context-aware setting recommendations"],
    bankingWorkflow: ["Configure application preferences", "Toggle demo and judge modes", "Manage notification preferences"],
    judgeObservations: ["Settings grouped by category", "Toggle switches for binary settings", "Role-aware default configurations"],
    estimatedTime: "20 sec",
    relatedPages: [{ label: "Profile", path: "/profile" }, { label: "Help Center", path: "/help" }],
    recommendedNext: { label: "Notification Center", path: "/notifications" },
    tourOrder: undefined,
    whyJudgeCares: "Clean settings UI with role-aware defaults demonstrates attention to user experience and personalization.",
    innovationHighlight: "Role-based default settings that adapt to loan officer, manager, or executive contexts automatically.",
    simpleExplanation: "Configure your preferences — demo mode, judge mode, notification settings, and account information.",
    highlightSelector: "main",
    icon: "settings",
  },
  {
    id: "help",
    title: "Help Center",
    path: "/help",
    purpose: "Comprehensive help resource with FAQs, keyboard shortcuts, video tutorials, feature guides, glossary, AI assistant, and support contact.",
    businessValue: "Self-service support reduces help desk tickets by providing immediate answers to common questions and comprehensive documentation.",
    aiFeatures: ["AI assistant for contextual help", "Search across all help content"],
    bankingWorkflow: ["Search for help articles and guides", "Browse FAQs and video tutorials", "Contact support for complex issues"],
    judgeObservations: ["Searchable help content", "Categorized help sections", "Video tutorial integration", "Interactive walkthrough option"],
    estimatedTime: "30 sec",
    relatedPages: [{ label: "Settings", path: "/settings" }, { label: "Profile", path: "/profile" }],
    recommendedNext: { label: "Settings", path: "/settings" },
    tourOrder: undefined,
    whyJudgeCares: "Comprehensive self-service help with AI assistant shows the platform is designed for real user adoption.",
    innovationHighlight: "Context-aware help articles that adapt suggestions based on the user's current page and role.",
    simpleExplanation: "Find answers to common questions, watch video tutorials, browse feature guides, or contact support.",
    highlightSelector: "main",
    icon: "helpCircle",
  },
  {
    id: "profile",
    title: "Profile",
    path: "/profile",
    purpose: "User profile management with personal details, activity timeline, performance metrics, and account management for both staff and customers.",
    businessValue: "Unified profile view that shows user information, recent activity, and key metrics in one consolidated dashboard.",
    aiFeatures: ["AI-generated activity summary", "Performance metrics with trend insights"],
    bankingWorkflow: ["View and edit personal information", "Review recent activity timeline", "Access key performance metrics"],
    judgeObservations: ["Clean profile header with avatar and details", "Activity timeline with action types", "Performance metrics and KPIs"],
    estimatedTime: "20 sec",
    relatedPages: [{ label: "Settings", path: "/settings" }, { label: "Help Center", path: "/help" }],
    recommendedNext: { label: "Settings", path: "/settings" },
    tourOrder: undefined,
    whyJudgeCares: "Unified staff/customer profile with activity timeline shows the platform supports both internal and external user management.",
    innovationHighlight: "Role-aware profile views that show different metrics and actions for loan officers, managers, and customers.",
    simpleExplanation: "Your profile — view personal details, recent activity, performance metrics, and access settings.",
    highlightSelector: "main",
    icon: "user",
  },
];

export function getGuide(pathname: string): GuideEntry | undefined {
  const normalized = pathname.split("?")[0];
  return GUIDES.find(
    (g) =>
      normalized === g.path ||
      (g.path.includes("[") && matchDynamicRoute(normalized, g.path))
  );
}

function matchDynamicRoute(path: string, pattern: string): boolean {
  const patternParts = pattern.split("/");
  const pathParts = path.split("/");
  if (patternParts.length !== pathParts.length) return false;
  return patternParts.every((p, i) => p.startsWith("[") || p === pathParts[i]);
}

export function getRecommendedNext(pathname: string): { label: string; path: string } | null {
  const guide = getGuide(pathname);
  return guide?.recommendedNext ?? null;
}

// ─── Tour Step Configuration ─────────────────────────────────────────

export const TOUR_ROLE_MAP: Record<string, string> = {
  "landing": "customer",
  "customer-dashboard": "customer",
  "customer-business": "customer",
  "customer-documents": "customer",
  "consent-page": "customer",
  "customer-apply": "customer",
  "customer-status": "customer",
  "loan-officer-dashboard": "loan-officer",
  "health-card": "loan-officer",
  "applications-list": "loan-officer",
  "customer-360": "manager",
  "explainable-ai": "loan-officer",
  "document-intelligence": "loan-officer",
  "credit-memo": "loan-officer",
  "decision-timeline": "loan-officer",
  "manager-dashboard": "manager",
  "portfolio-intelligence": "manager",
  "financial-inclusion": "manager",
  "executive-dashboard": "executive",
  "executive-analytics": "executive",
  "reporting-center": "executive",
  "audit-center": "executive",
  "business-impact": "customer",
  "demo-complete": "customer",
};

export const GUIDE_MAP: Record<string, string> = {
  "landing": "/",
  "customer-dashboard": "/customer/dashboard",
  "customer-business": "/customer/business",
  "customer-documents": "/customer/documents",
  "consent-page": "/customer/dashboard?consent",
  "customer-apply": "/customer/apply",
  "customer-status": "/customer/status",
  "loan-officer-dashboard": "/command-center?role=loan-officer",
  "health-card": "/applications/app-1001?role=loan-officer",
  "applications-list": "/applications?role=loan-officer",
  "customer-360": "/portfolio/msme-aurora?role=manager",
  "explainable-ai": "/applications/app-1001?role=loan-officer&view=explain",
  "document-intelligence": "/applications/app-1001?role=loan-officer&view=documents",
  "credit-memo": "/applications/app-1001/production-memo?role=loan-officer",
  "decision-timeline": "/applications/app-1001/timeline?role=loan-officer",
  "manager-dashboard": "/command-center?role=manager",
  "portfolio-intelligence": "/portfolio?role=manager",
  "financial-inclusion": "/portfolio?role=manager&view=inclusion",
  "executive-dashboard": "/reporting/executive?role=manager",
  "executive-analytics": "/reporting?role=manager&view=analytics",
  "reporting-center": "/reporting?role=manager",
  "audit-center": "/audit?role=manager",
  "business-impact": "/business-impact",
  "demo-complete": "/demo-complete",
  "credit-memo-internal": "/applications/app-1001/memo",
  "notifications": "/notifications",
  "settings": "/settings",
  "help": "/help",
  "profile": "/profile",
  "customer-support": "/customer/support",
  "applications-queue": "/applications",
};

export const TOUR_STEPS: TourStep[] = [
  {
    pageId: "landing",
    title: "Welcome to NexusNova",
    description: "An AI-powered MSME Lending Platform built for IDBI Innovate Hackathon. This landing page shows live portfolio metrics, role selection, and demo mode entry.",
    businessValue: "First impression matters — this page demonstrates the full platform breadth in under 30 seconds.",
    whyJudgeCares: "This page shows the depth and polish of the entire platform before you even log in.",
    innovationHighlight: "Real-time portfolio aggregation using pure in-memory computation — no backend required.",
    estimatedTime: "30 sec",
    simpleExplanation: "This is the front door. It shows live portfolio numbers, lets you pick a role, and seeds demo data with one click.",
    highlightSelector: "header",
    path: "/",
  },
  {
    pageId: "customer-dashboard",
    title: "Customer Dashboard",
    description: "360-degree customer view with active loan applications, document status, AI support, and dynamic loan recommendations.",
    businessValue: "Self-service portal reducing branch visits by 60% with real-time tracking and AI assistance.",
    whyJudgeCares: "Full customer self-service with AI chat — a key requirement for paperless banking innovation.",
    innovationHighlight: "BANK AI chatbot provides contextual support using pure TypeScript pattern matching — no external APIs.",
    estimatedTime: "45 sec",
    simpleExplanation: "Customers see everything about their loans, upload documents, and chat with AI support.",
    highlightSelector: "[class*='glass']",
    path: "/customer/dashboard",
  },
  {
    pageId: "customer-business",
    title: "Business Registration",
    description: "MSME owners register their business, providing GST, PAN, UPI, bank details, and EPFO information — all in one place.",
    businessValue: "Zero-paper, zero-branch-visit onboarding that captures alternate data from 5+ sources in minutes.",
    whyJudgeCares: "Complete digital registration flow — no paper, no branch visit, captures all regulatory data.",
    innovationHighlight: "Real-time GST validation, PAN verification, and UPI linkage — single unified registration form.",
    estimatedTime: "30 sec",
    simpleExplanation: "MSME owners register their business and connect their digital footprint — GST, UPI, bank, and EPFO.",
    highlightSelector: "form",
    path: "/customer/business",
  },
  {
    pageId: "customer-documents",
    title: "Document Upload Center",
    description: "Upload GST returns, bank statements, ITRs, and KYC documents with AI-powered extraction and validation.",
    businessValue: "AI document intelligence reduces manual data entry by 80% with automatic extraction and confidence scoring.",
    whyJudgeCares: "Document intelligence is the hardest AI problem in MSME lending — showing automated extraction with confidence scoring.",
    innovationHighlight: "Simulated document AI that extracts GST, revenue, and bank data with per-field confidence — no external OCR needed.",
    estimatedTime: "30 sec",
    simpleExplanation: "Upload documents and AI reads them automatically — no manual data entry needed by bank staff.",
    highlightSelector: "[class*='grid']",
    path: "/customer/documents",
  },
  {
    pageId: "consent-page",
    title: "Alternate Data Consent",
    description: "Customers grant consent for NexusNova to access their GST, UPI, Account Aggregator, and EPFO data — the foundation of alternate data credit assessment.",
    businessValue: "Customer-permissioned data access ensures regulatory compliance (RBI AA framework) while enabling comprehensive credit assessment.",
    whyJudgeCares: "Demonstrates consent-based data architecture compliant with RBI's Account Aggregator framework — critical for production banking.",
    innovationHighlight: "One-click consent for 5 data sources replaces 20+ pages of manual financial documentation.",
    estimatedTime: "30 sec",
    simpleExplanation: "Customers give permission to access their digital financial data — the foundation of AI credit assessment.",
    highlightSelector: "[class*='glass']",
    path: "/customer/dashboard?consent",
  },
  {
    pageId: "customer-apply",
    title: "Loan Application",
    description: "Digital loan application with MSME registration, financial data entry, and AI-suggested loan products.",
    businessValue: "Paperless, branchless applications capturing regulatory data in under 3 minutes.",
    whyJudgeCares: "Complete digital onboarding flow — no paper, no branch visit, fully compliant.",
    innovationHighlight: "AI-suggested loan products adapt in real-time to the MSME profile entered.",
    estimatedTime: "30 sec",
    simpleExplanation: "A smart form that asks for business details and suggests the best loan product automatically.",
    highlightSelector: "form",
    path: "/customer/apply",
  },
  {
    pageId: "customer-status",
    title: "Application Tracker",
    description: "Real-time tracking of all applications with status, SLA countdown, and AI readiness prediction.",
    businessValue: "Complete transparency with SLA tracking, reducing customer follow-up calls by 70%.",
    whyJudgeCares: "SLA tracking with AI readiness prediction shows practical banking workflow integration.",
    innovationHighlight: "AI readiness score predicts auto-approval potential before a human reviews the case.",
    estimatedTime: "30 sec",
    simpleExplanation: "See all applications in one place — what's approved, pending, and how long until a decision.",
    highlightSelector: "[class*='space-y']",
    path: "/customer/status",
  },
  {
    pageId: "customer-support",
    title: "Customer Support",
    description: "AI-powered customer support center with BANK AI chatbot for instant help, knowledge base, and escalation options.",
    businessValue: "24/7 self-service support resolving 80% of queries without human intervention — reducing support costs by 60%.",
    whyJudgeCares: "AI-powered support shows the platform handles the full customer lifecycle — not just loan origination.",
    innovationHighlight: "BANK AI chatbot provides contextual support using pure TypeScript pattern matching — no external APIs.",
    estimatedTime: "20 sec",
    simpleExplanation: "Get help instantly with AI chat, browse knowledge base, or escalate to a human agent.",
    highlightSelector: "main",
    path: "/customer/support",
  },
  {
    pageId: "loan-officer-dashboard",
    title: "Loan Officer Dashboard",
    description: "Command center showing urgent applications, early warnings, portfolio exposure, and SLA breaches — all AI-prioritized.",
    businessValue: "Single-pane-of-glass monitoring reducing response time to critical events by 90%.",
    whyJudgeCares: "Where AI meets banking operations — early warnings, SLA tracking, and role-based views.",
    innovationHighlight: "Real-time early warning system detects MSME financial distress from revenue patterns.",
    estimatedTime: "45 sec",
    simpleExplanation: "A single dashboard where loan officers see urgent cases, portfolio alerts, and SLA deadlines.",
    highlightSelector: "[class*='grid']",
    path: "/command-center?role=loan-officer",
  },
  {
    pageId: "health-card",
    title: "MSME Financial Health Card",
    description: "Generates a multidimensional Financial Health Score using GST, UPI, Account Aggregator, EPFO, and Utility data — one unified card replacing 20+ pages of financial analysis.",
    businessValue: "Enables credit assessment for credit-invisible MSMEs, unlocking a ₹50 lakh crore lending opportunity currently served by informal lenders.",
    whyJudgeCares: "The core PS-3 innovation — a single-page credit decision that every bank officer can understand in under 60 seconds.",
    innovationHighlight: "AI computes health score, risk band, credit limit, and factor contribution from 5+ alternate data sources in real-time.",
    estimatedTime: "45 sec",
    simpleExplanation: "One unified AI-powered card showing health score, risk band, credit limit, and what matters most — replacing 20+ pages of financial analysis.",
    highlightSelector: "[class*='grid']",
    path: "/applications/app-1001?role=loan-officer",
  },
  {
    pageId: "applications-list",
    title: "Alternate Data Dashboard",
    description: "Overview of all loan applications showing alternate data intelligence, coverage gaps, and assessment readiness per MSME.",
    businessValue: "Bulk visibility into alternate data coverage across applications enables efficient triage and priority management.",
    whyJudgeCares: "Demonstrates how alternate data intelligence scales across the entire lending pipeline, not just individual cases.",
    innovationHighlight: "AI readiness indicators on every application show which MSMEs have sufficient alternate data for automated processing.",
    estimatedTime: "30 sec",
    simpleExplanation: "See all applications with their alternate data readiness — instantly know which MSMEs can be assessed automatically.",
    highlightSelector: "[class*='space-y']",
    path: "/applications?role=loan-officer",
  },
  {
    pageId: "applications-queue",
    title: "Application Queue",
    description: "Central queue of all loan applications with AI-powered prioritization, alternate data coverage, and quick-action workflows.",
    businessValue: "Enables efficient triage by showing AI readiness scores and priority indicators for every application at a glance.",
    whyJudgeCares: "AI-prioritized application queue shows how the platform scales from individual cases to portfolio-wide management.",
    innovationHighlight: "AI readiness scores let officers instantly know which applications have enough data for automated processing.",
    estimatedTime: "30 sec",
    simpleExplanation: "See all applications with their AI readiness status — filter, sort, and open any application for detailed review.",
    highlightSelector: "[class*='space-y']",
    path: "/applications?role=loan-officer",
  },
  {
    pageId: "customer-360",
    title: "Customer 360",
    description: "Deep-dive into an MSME with full financial profile, risk analysis, documents, relationship timeline, and alternate data visualization.",
    businessValue: "Complete customer view enabling informed decisions with all data in one screen — reducing research time by 80%.",
    whyJudgeCares: "Complete customer data aggregation — financials, risk, documents, and timeline unified in one view.",
    innovationHighlight: "Risk band progression timeline shows how risk profile evolved month-over-month with alternate data signals.",
    estimatedTime: "45 sec",
    simpleExplanation: "Everything about a business — finances, risk, documents, and full history with the bank in one screen.",
    highlightSelector: "main",
    path: "/portfolio/msme-aurora?role=manager",
  },
  {
    pageId: "explainable-ai",
    title: "Explainable AI",
    description: "Every AI decision includes factor contribution (what matters most), confidence scores (how sure AI is), and improvement recommendations (how to get better terms).",
    businessValue: "Builds trust through transparency — bank officers must understand and justify every AI recommendation to regulators.",
    whyJudgeCares: "Satisfies RBI guidelines on responsible AI with full explainability and audit trail — critical for production deployment.",
    innovationHighlight: "Visual factor breakdown shows exactly which data sources drive the score — GST consistency, cash flow stability, revenue trend, debt levels.",
    estimatedTime: "45 sec",
    simpleExplanation: "AI shows its work — which factors matter, how confident it is, and what the business can do to improve.",
    highlightSelector: "[class*='space-y']",
    path: "/applications/app-1001?role=loan-officer&view=explain",
  },
  {
    pageId: "document-intelligence",
    title: "Document Intelligence",
    description: "AI extracts key financial data from uploaded documents — GST returns, bank statements, ITRs — with per-field confidence scoring and fraud detection.",
    businessValue: "Reduces manual data entry by 80% and detects document tampering automatically, preventing fraud before it happens.",
    whyJudgeCares: "Document intelligence is the hardest AI problem in MSME lending — automated extraction with confidence scoring is production-ready.",
    innovationHighlight: "Per-field confidence scoring across GST revenue, bank balances, and income — AI knows what it knows and what it doesn't.",
    estimatedTime: "30 sec",
    simpleExplanation: "AI reads uploaded documents and extracts key numbers automatically — with confidence scores for every field.",
    highlightSelector: "[class*='space-y']",
    path: "/applications/app-1001?role=loan-officer&view=documents",
  },
  {
    pageId: "credit-memo",
    title: "Credit Memo",
    description: "Bank-grade AI-generated credit memo with risk assessment, financial ratios, peer comparison, and recommendation — replaces 4 hours of analyst work.",
    businessValue: "Saves 3-4 hours per application and ensures consistent, compliant credit memos every time.",
    whyJudgeCares: "AI-generated credit memos are the holy grail of banking — bank-ready, not just a demo.",
    innovationHighlight: "Matches real bank memo standards with proper risk ratings, financial ratios, peer comparison, and auditor notes.",
    estimatedTime: "45 sec",
    simpleExplanation: "AI writes a complete bank-grade credit memo in seconds — normally takes an analyst 3-4 hours.",
    highlightSelector: "main",
    path: "/applications/app-1001/production-memo?role=loan-officer",
  },
  {
    pageId: "decision-timeline",
    title: "Decision Timeline",
    description: "Complete audit trail of the loan decision process — from application submission through AI analysis, committee review, and final human decision with override rationale.",
    businessValue: "Full transparency into every step of the lending process with timestamps, decisions, and AI rationale at each stage.",
    whyJudgeCares: "Shows the complete decision journey — not just the outcome, but how AI and human collaboration reached it.",
    innovationHighlight: "AI rationale snapshots at every decision stage — frozen in time for regulatory audit even if models change.",
    estimatedTime: "30 sec",
    simpleExplanation: "See every step of the loan decision — what happened, when, and why — from application to final approval.",
    highlightSelector: "[class*='space-y']",
    path: "/applications/app-1001/timeline?role=loan-officer",
  },
  {
    pageId: "manager-dashboard",
    title: "Manager Dashboard",
    description: "Portfolio-level view with risk heatmaps, sector comparisons, exposure treemaps, and early warning system for deteriorating MSMEs.",
    businessValue: "Enables proactive risk management — catches potential NPAs 2-3 months earlier, reducing credit losses by 40%.",
    whyJudgeCares: "Enterprise portfolio monitoring that enables proactive risk management — not just reactive reporting.",
    innovationHighlight: "Real-time early warning system across the entire portfolio — detects sector concentration and risk migration before losses materialize.",
    estimatedTime: "45 sec",
    simpleExplanation: "See your entire portfolio — risky sectors, branch performance, and emerging problems before they become losses.",
    highlightSelector: "[class*='grid']",
    path: "/command-center?role=manager",
  },
  {
    pageId: "portfolio-intelligence",
    title: "Portfolio Intelligence",
    description: "Enterprise portfolio monitoring with risk heatmaps, sector comparisons, exposure treemaps, and migration timelines.",
    businessValue: "Proactive risk management identifying concentration, migration trends, and early warnings before losses materialize.",
    whyJudgeCares: "Enterprise-grade visualizations most production banking platforms don't have.",
    innovationHighlight: "Six chart types — donut, heatmap, treemap, bar, migration timeline, branch comparison — all interactive and animated.",
    estimatedTime: "1 min",
    simpleExplanation: "See your entire loan portfolio at a glance — which sectors are risky, which branches are performing, and where problems are emerging.",
    highlightSelector: "[class*='grid']",
    path: "/portfolio?role=manager",
  },
  {
    pageId: "financial-inclusion",
    title: "Financial Inclusion Dashboard",
    description: "Track financial inclusion metrics — how many credit-invisible MSMEs are being served, alternate data coverage rates, and progress toward inclusive banking goals.",
    businessValue: "Measures and demonstrates the social impact of AI-powered lending — serving the 60% of MSMEs previously excluded from formal credit.",
    whyJudgeCares: "The ultimate measure of PS-3 success — demonstrating measurable progress in financial inclusion for credit-invisible MSMEs.",
    innovationHighlight: "Real-time inclusion metrics showing how alternate data bridges the credit gap for New-to-Credit and New-to-Bank enterprises.",
    estimatedTime: "30 sec",
    simpleExplanation: "Track how many previously excluded MSMEs are now accessing formal credit through alternate data intelligence.",
    highlightSelector: "[class*='grid']",
    path: "/portfolio?role=manager&view=inclusion",
  },
  {
    pageId: "executive-dashboard",
    title: "Executive Dashboard",
    description: "Board-ready dashboard with portfolio KPIs, risk distribution, sector analysis, and trend visualizations for C-suite leadership.",
    businessValue: "Real-time executive visibility into portfolio health, risk exposure, and growth trends — board-presentation quality.",
    whyJudgeCares: "Board-ready dashboards with premium charts — designed for C-suite presentation, not just operational use.",
    innovationHighlight: "Premium Recharts with gradient fills, custom tooltips, and dynamic imports — same tech stack as production analytics tools.",
    estimatedTime: "45 sec",
    simpleExplanation: "A boardroom-quality dashboard showing portfolio health, risk trends, and growth metrics — all updated in real-time.",
    highlightSelector: "[class*='grid']",
    path: "/reporting/executive?role=manager",
  },
  {
    pageId: "executive-analytics",
    title: "Executive Analytics",
    description: "Deep portfolio analytics: risk migration timelines, branch performance, credit exposure monitoring, dynamic credit limits, and what-if stress scenarios.",
    businessValue: "Enables data-driven strategic decisions with comprehensive analytics across the entire lending portfolio.",
    whyJudgeCares: "Demonstrates that the platform serves not just operations but strategic decision-making at the highest level.",
    innovationHighlight: "Dynamic credit limit adjustments based on real-time portfolio health — AI that actively manages risk exposure.",
    estimatedTime: "45 sec",
    simpleExplanation: "Deep analytics showing portfolio trends, branch performance, and risk migration patterns for strategic decision-making.",
    highlightSelector: "[class*='grid']",
    path: "/reporting?role=manager&view=analytics",
  },
  {
    pageId: "reporting-center",
    title: "Reporting Center",
    description: "Self-service reporting hub with portfolio summaries, risk reports, sector analysis, and AI-generated executive summaries.",
    businessValue: "Reduces analyst report generation by 95% with pre-built templates and AI insights.",
    whyJudgeCares: "Self-service reporting with AI summaries — designed for real banking operations, not just demos.",
    innovationHighlight: "Reports categorized as lendable (investor-ready) and managed (internal) — matches production banking report taxonomy.",
    estimatedTime: "45 sec",
    simpleExplanation: "Find any report — portfolio summaries, risk reports, sector analysis with AI-written executive summaries.",
    highlightSelector: "[class*='grid']",
    path: "/reporting?role=manager",
  },
  {
    pageId: "audit-center",
    title: "Audit Center",
    description: "Immutable audit logs with AI rationale snapshots, role-based access, and exportable compliance reports.",
    businessValue: "Regulatory compliance-ready logs satisfying RBI and statutory audit requirements.",
    whyJudgeCares: "Immutable audit logs with AI rationale — shows the system is bank-ready, not just a demo.",
    innovationHighlight: "AI rationale frozen at decision time — full explainability preserved for regulators even if models change.",
    estimatedTime: "45 sec",
    simpleExplanation: "Every decision recorded with proof — who decided, what AI said, and why. Ready for regulators.",
    highlightSelector: "table",
    path: "/audit?role=manager",
  },
  {
    pageId: "business-impact",
    title: "Business Impact",
    description: "5 days → 2 hours processing. 60% market expansion. 80% cost reduction. 100% explainable. Zero infrastructure. This is what NexusNova delivers.",
    businessValue: "ROI within 6 months through reduced processing costs, expanded portfolio, and lower credit losses.",
    whyJudgeCares: "Quantifiable business impact that demonstrates real-world value beyond technical innovation.",
    innovationHighlight: "Complete transformation of MSME lending — from paper-based 5-day process to AI-powered 2-hour decision cycle.",
    estimatedTime: "30 sec",
    simpleExplanation: "Measurable outcomes: 5-day processing to 2 hours, 60% market expansion, 80% cost reduction, zero new infrastructure.",
    highlightSelector: "main",
    path: "/business-impact",
  },
  {
    pageId: "demo-complete",
    title: "Demo Complete",
    description: "You have successfully completed the comprehensive NexusNova Credit Intelligence OS guided tour — exploring the complete AI-powered MSME lending journey.",
    businessValue: "Full platform evaluation completed — ready for judge assessment and scoring.",
    whyJudgeCares: "Complete end-to-end demonstration of AI-powered MSME lending from customer onboarding to executive analytics.",
    innovationHighlight: "One unified platform serving customers, loan officers, managers, and executives — each with role-appropriate views and tools.",
    estimatedTime: "—",
    simpleExplanation: "The guided tour is complete. You may now explore the prototype freely or restart the tour.",
    highlightSelector: "main",
    path: "/demo-complete",
  },
];

export const CHECKLIST: ChecklistItem[] = [
  { id: "landing", label: "Welcome & Landing", path: "/" },
  { id: "customer-dashboard", label: "Customer Dashboard", path: "/customer/dashboard" },
  { id: "customer-business", label: "Business Registration", path: "/customer/business" },
  { id: "customer-documents", label: "Document Upload", path: "/customer/documents" },
  { id: "consent-page", label: "Alternate Data Consent", path: "/customer/dashboard" },
  { id: "customer-apply", label: "Loan Application", path: "/customer/apply" },
  { id: "customer-status", label: "Application Status", path: "/customer/status" },
  { id: "customer-support", label: "Customer Support", path: "/customer/support" },
  { id: "loan-officer-dashboard", label: "Loan Officer Dashboard", path: "/command-center?role=loan-officer" },
  { id: "health-card", label: "MSME Financial Health Card", path: "/applications/app-1001?role=loan-officer" },
  { id: "applications-list", label: "Alternate Data Dashboard", path: "/applications?role=loan-officer" },
  { id: "customer-360", label: "Customer 360", path: "/portfolio/msme-aurora?role=manager" },
  { id: "explainable-ai", label: "Explainable AI", path: "/applications/app-1001?role=loan-officer" },
  { id: "document-intelligence", label: "Document Intelligence", path: "/applications/app-1001?role=loan-officer" },
  { id: "credit-memo", label: "Credit Memo", path: "/applications/app-1001/production-memo?role=loan-officer" },
  { id: "decision-timeline", label: "Decision Timeline", path: "/applications/app-1001/timeline?role=loan-officer" },
  { id: "manager-dashboard", label: "Manager Dashboard", path: "/command-center?role=manager" },
  { id: "portfolio-intelligence", label: "Portfolio Intelligence", path: "/portfolio?role=manager" },
  { id: "financial-inclusion", label: "Financial Inclusion", path: "/portfolio?role=manager" },
  { id: "executive-dashboard", label: "Executive Dashboard", path: "/reporting/executive?role=manager" },
  { id: "executive-analytics", label: "Executive Analytics", path: "/reporting?role=manager" },
  { id: "reporting-center", label: "Reporting Center", path: "/reporting?role=manager" },
  { id: "audit-center", label: "Audit Trail", path: "/audit?role=manager" },
  { id: "business-impact", label: "Business Impact", path: "/business-impact" },
  { id: "demo-complete", label: "Demo Complete", path: "/demo-complete" },
];

export const AI_TOOLTIPS: Record<string, AiTooltipData> = {
  "financial-health": {
    label: "Financial Health Score",
    description: "AI evaluates the overall financial stability of a business by analyzing revenue trends, GST consistency, cash flow patterns, and debt levels.",
    dataSources: ["GST returns — tax filing consistency", "Bank statements — cash flow patterns", "Revenue trend — growth trajectory", "Debt-to-income ratio — existing obligations"],
    confidence: 96,
    businessMeaning: "Higher scores mean stronger financial health. Scores above 75 indicate low default risk. Scores below 50 require additional collateral.",
  },
  "repayment-risk": {
    label: "Repayment Risk",
    description: "AI predicts the likelihood of timely loan repayment based on historical transaction behavior and cash flow stability.",
    dataSources: ["EMI payment history — past repayment behavior", "Failed transactions — financial stress signals", "Cash flow volatility — income stability", "Revenue consistency — business predictability"],
    confidence: 94,
    businessMeaning: "Lower risk scores mean higher repayment confidence. Scores below 30 are high risk and may require additional guarantees.",
  },
  "fraud-risk": {
    label: "Fraud Risk Score",
    description: "AI detects potential fraud by analyzing document consistency, data anomalies, and unusual patterns in financial submissions.",
    dataSources: ["Document confidence scores — AI verification quality", "Data mismatch detection — inconsistencies across sources", "Tamper indicators — document alteration flags", "Concentration anomalies — unusual transaction patterns"],
    confidence: 92,
    businessMeaning: "Higher scores suggest higher fraud probability. Scores above 60 require enhanced due diligence before approval.",
  },
  "business-growth": {
    label: "Business Growth Forecast",
    description: "AI projects future business growth by analyzing revenue trends, GST filing history, and digital transaction growth.",
    dataSources: ["Revenue trend — historical growth rate", "GST filing consistency — compliance reliability", "UPI transaction growth — digital adoption", "Customer concentration — dependency risk"],
    confidence: 88,
    businessMeaning: "Positive forecast means expanding business. Used to determine loan tenure and eligibility for growth-linked loan products.",
  },
  "cash-flow": {
    label: "Cash Flow Stability",
    description: "AI assesses how consistently a business generates cash and whether it can comfortably cover existing loan obligations.",
    dataSources: ["Monthly inflow patterns — income seasonality", "Obligation coverage — ability to pay existing debts", "Revenue volatility — income fluctuation risk"],
    confidence: 91,
    businessMeaning: "Stable cash flow means reliable loan servicing. Volatility above 30% triggers additional financial scrutiny.",
  },
  "credit-limit": {
    label: "Dynamic Credit Limit",
    description: "AI computes the optimal loan amount a business can safely borrow based on financial capacity, risk profile, and existing debt.",
    dataSources: ["Average monthly revenue — repayment capacity", "Revenue volatility — risk buffer needed", "Customer concentration — diversification risk", "Existing obligations — current debt burden"],
    confidence: 93,
    businessMeaning: "The safe limit is the recommended loan amount. The max limit is the ceiling under current financials — exceeding it increases risk.",
  },
  "ai-readiness": {
    label: "AI Readiness Score",
    description: "AI determines whether an application has enough reliable data to be processed automatically or needs human review.",
    dataSources: ["Document completeness — all required docs uploaded", "Data confidence — AI trust level in extracted data", "Risk thresholds — score within acceptable ranges", "Fraud indicators — no suspicious patterns detected"],
    confidence: 95,
    businessMeaning: "AI-ready applications can be auto-approved. Manual review triggers when data quality or risk scores fall below thresholds.",
  },
  "portfolio-health": {
    label: "Portfolio Health Score",
    description: "AI aggregates the health of all MSME loans in the portfolio into a single score, highlighting overall risk exposure.",
    dataSources: ["Individual MSME health scores — per-business assessment", "Risk band distribution — portfolio risk composition", "Early warning density — emerging problem count", "Sector concentration — diversification quality"],
    confidence: 97,
    businessMeaning: "Scores above 80 = healthy portfolio. Scores below 60 = management attention required. Trend direction matters more than absolute score.",
  },
};

export const FEATURE_DISCOVERY = [
  { id: "production-memo", label: "Production Credit Memo", path: "/applications/app-1001/production-memo" },
  { id: "audit-center", label: "Audit Trail", path: "/audit" },
  { id: "executive-dashboard", label: "Executive Dashboard", path: "/reporting/executive" },
  { id: "stress-simulator", label: "Stress Simulator", path: "/applications/app-1001" },
  { id: "credit-committee", label: "AI Credit Committee", path: "/applications/app-1001" },
  { id: "customer-360", label: "Customer 360 View", path: "/portfolio/msme-aurora" },
];

export const TOTAL_TOUR_STEPS = TOUR_STEPS.length;
