import type { GuideEntry, TourStep, ChecklistItem, AiTooltipData } from "./types";

export const GUIDES: GuideEntry[] = [
  {
    id: "home",
    title: "Home / Landing",
    path: "/",
    purpose: "Launchpad for the entire NexusNova Credit Intelligence OS — role selection, live metrics, and demo mode entry.",
    businessValue: "Demonstrates the breadth of the platform in under 30 seconds with real-time portfolio exposure, risk scores, and sector coverage.",
    aiFeatures: ["Live aggregate intelligence from portfolio computation", "AI-powered readiness indicators on role cards"],
    bankingWorkflow: ["Role selection (Customer / Loan Officer / Manager)", "Live metric preview without navigation", "One-click demo data seeding"],
    judgeObservations: ["CountUp animations on all four live metrics", "Glass morphism cards with hover effects", "Gradient hero background with slow animation", "Role cards expand into full portals", "Demo mode seeds complete in-memory data"],
    estimatedTime: "30 sec",
    relatedPages: [{ label: "Customer Dashboard", path: "/customer/dashboard" }, { label: "Command Center", path: "/command-center" }],
    recommendedNext: { label: "Customer Portal", path: "/customer/dashboard" },
    tourOrder: 1,
    whyJudgeCares: "First impression matters — this page shows the depth of the platform in under 30 seconds with animated metrics and polished UI.",
    innovationHighlight: "Real-time portfolio aggregation on a static landing page using pure in-memory computation — no backend required.",
    simpleExplanation: "This is the front door. It shows live portfolio numbers, lets you pick a role, and seeds demo data with one click.",
    highlightSelector: "header",
    icon: "layout",
  },
  {
    id: "customer-dashboard",
    title: "Customer Dashboard",
    path: "/customer/dashboard",
    purpose: "360-degree customer view with active loan applications, document status, support access, and AI-powered loan recommendations.",
    businessValue: "Self-service portal that reduces branch visits by 60% and provides real-time application tracking with AI assistance.",
    aiFeatures: ["BANK AI chatbot for instant support", "AI readiness scoring for submitted applications", "Dynamic loan recommendations based on profile"],
    bankingWorkflow: ["View submitted applications and status", "Upload required documents", "Chat with AI support", "Track SLA timelines"],
    judgeObservations: ["Customer 360 data aggregation", "AI chat integration with contextual answers", "Document status tracking per application", "Real-time SLA countdown indicators"],
    estimatedTime: "45 sec",
    relatedPages: [{ label: "Apply for Loan", path: "/customer/apply" }, { label: "Application Status", path: "/customer/status" }],
    recommendedNext: { label: "Apply for Loan", path: "/customer/apply" },
    tourOrder: 2,
    whyJudgeCares: "Demonstrates full customer self-service — a key requirement for paperless banking. AI chat shows practical LLM integration.",
    innovationHighlight: "BANK AI chatbot provides contextual support without external APIs — pure TypeScript pattern matching that feels intelligent.",
    simpleExplanation: "Customers see all their loans, documents, and can chat with AI support. No more visiting a branch.",
    highlightSelector: "[class*='glass']",
    icon: "user",
  },
  {
    id: "customer-apply",
    title: "Loan Application",
    path: "/customer/apply",
    purpose: "Digital loan application form with MSME registration, financial data entry, and product selection.",
    businessValue: "Paperless, branchless loan applications that capture all regulatory-required data in under 3 minutes.",
    aiFeatures: ["Real-time GST PAN validation hints", "AI-suggested loan products based on profile"],
    bankingWorkflow: ["MSME profile registration", "Loan product selection", "Financial information submission"],
    judgeObservations: ["Form validation and error handling", "Step-by-step application flow", "Mobile-responsive form layout"],
    estimatedTime: "30 sec",
    relatedPages: [{ label: "Upload Documents", path: "/customer/documents" }, { label: "Application Status", path: "/customer/status" }],
    recommendedNext: { label: "Upload Documents", path: "/customer/documents" },
    tourOrder: 3,
    whyJudgeCares: "Shows complete digital onboarding flow — no paper, no branch visit, fully compliant with regulatory data capture.",
    innovationHighlight: "AI-suggested loan products adapt in real-time to the MSME profile entered — predictive configuration without database lookups.",
    simpleExplanation: "A smart form that asks for business details and suggests the best loan product automatically.",
    highlightSelector: "form",
    icon: "file",
  },
  {
    id: "customer-documents",
    title: "Document Upload",
    path: "/customer/documents",
    purpose: "Document management interface for uploading GST returns, bank statements, ITRs, and KYC documents.",
    businessValue: "AI-powered document intelligence extracts key financial data automatically, reducing manual data entry by 80%.",
    aiFeatures: ["Document intelligence with confidence scoring", "Automatic data extraction from uploaded documents", "Fraud detection via document tamper analysis"],
    bankingWorkflow: ["Upload required document categories", "AI extracts and validates data", "Confidence scoring per document", "Request resubmission if confidence is low"],
    judgeObservations: ["Document intelligence confidence indicators", "Status progression per document", "AI extraction preview of key fields"],
    estimatedTime: "30 sec",
    relatedPages: [{ label: "Application Status", path: "/customer/status" }, { label: "Apply for Loan", path: "/customer/apply" }],
    recommendedNext: { label: "Application Status", path: "/customer/status" },
    tourOrder: 4,
    whyJudgeCares: "Document intelligence is the hardest AI problem in MSME lending — this shows automated extraction with confidence scoring.",
    innovationHighlight: "Simulated document AI that extracts GST, revenue, and bank data with per-field confidence — no external OCR needed.",
    simpleExplanation: "Upload documents and AI reads them automatically — no manual data entry needed by bank staff.",
    highlightSelector: "[class*='grid']",
    icon: "upload",
  },
  {
    id: "customer-status",
    title: "Application Tracker",
    path: "/customer/status",
    purpose: "Real-time application tracking dashboard showing all submitted applications with status, SLA, and next steps.",
    businessValue: "Complete transparency into loan processing with SLA tracking, reducing customer follow-up calls by 70%.",
    aiFeatures: ["AI readiness prediction before officer review", "Estimated approval time based on AI analysis"],
    bankingWorkflow: ["View all applications in one place", "Track SLA compliance per stage", "View AI readiness status"],
    judgeObservations: ["Application status badges with color coding", "SLA countdown timers", "AI readiness indicators per application"],
    estimatedTime: "30 sec",
    relatedPages: [{ label: "Command Center", path: "/command-center" }, { label: "Customer Dashboard", path: "/customer/dashboard" }],
    recommendedNext: { label: "Loan Officer Workspace", path: "/applications/app-1001?role=loan-officer" },
    tourOrder: 5,
    whyJudgeCares: "SLA tracking with AI readiness prediction shows practical banking workflow integration — not just a demo feature.",
    innovationHighlight: "AI readiness score predicts if an application can be auto-approved before a human ever looks at it.",
    simpleExplanation: "See all your applications in one place — what's approved, what's pending, and how long until a decision.",
    highlightSelector: "[class*='space-y']",
    icon: "clock",
  },
  {
    id: "command-center",
    title: "Command Center",
    path: "/command-center",
    purpose: "AI-powered operational hub for loan officers and managers showing urgent applications, early warnings, portfolio exposure, and SLA breaches.",
    businessValue: "Single-pane-of-glass monitoring reduces response time to critical events by 90% with real-time alerts.",
    aiFeatures: ["AI portfolio scan with health scoring", "Early warning detection from financial signals", "Confidence indicators on portfolio metrics", "AI-powered SLA breach prediction"],
    bankingWorkflow: ["Monitor urgent applications requiring immediate attention", "Track early warning alerts across portfolio", "Review portfolio exposure by MSME", "Manage SLA compliance"],
    judgeObservations: ["Confidence indicator bars with four metrics", "Real-time early warning alert system", "Portfolio exposure cards with risk band badges", "Role-adaptive view (officer vs manager)"],
    estimatedTime: "45 sec",
    relatedPages: [{ label: "Applications", path: "/applications" }, { label: "Portfolio", path: "/portfolio" }],
    recommendedNext: { label: "Application Workspace", path: "/applications/app-1001?role=loan-officer" },
    tourOrder: 6,
    whyJudgeCares: "The command center is where AI meets banking operations — early warnings, SLA tracking, and role-based views in one screen.",
    innovationHighlight: "Real-time early warning system detects MSME financial distress from revenue volatility and transaction patterns.",
    simpleExplanation: "A single dashboard where loan officers see urgent cases, portfolio alerts, and SLA deadlines — all AI-prioritized.",
    highlightSelector: "[class*='grid']",
    icon: "monitor",
  },
  {
    id: "application-workspace",
    title: "Application Workspace",
    path: "/applications/[id]",
    purpose: "Complete loan application review workspace with AI intelligence, document evidence, committee simulation, and human decision workflow.",
    businessValue: "Reduces loan decision time from 5 days to under 2 hours with AI-powered analysis and explainable recommendations.",
    aiFeatures: ["Financial health scoring (GST, cash flow, revenue trend)", "Repayment risk estimation with EMI coverage analysis", "Fraud risk detection from document and data anomalies", "Multi-persona credit committee simulation", "Stress scenario simulation for adverse conditions"],
    bankingWorkflow: ["Review AI intelligence across 9 dimensions", "Inspect document evidence with confidence scores", "Review explainable recommendation with rationale", "Run what-if stress scenarios", "Record human decision with override rationale"],
    judgeObservations: ["AI explainability panel with factor breakdown", "Confidence indicators with animated bars", "Credit committee with multiple reviewer personas", "Stress simulator with real-time limit recalculation", "Human decision workflow with override tracking"],
    estimatedTime: "2 min",
    relatedPages: [{ label: "Production Memo", path: "/applications/app-1001/production-memo" }, { label: "Timeline", path: "/applications/app-1001/timeline" }, { label: "Portfolio", path: "/portfolio" }],
    recommendedNext: { label: "Production Credit Memo", path: "/applications/app-1001/production-memo?role=loan-officer" },
    tourOrder: 7,
    whyJudgeCares: "This is the most feature-rich page — 9 AI engines, simulated committee, stress testing, and explainability. The core innovation.",
    innovationHighlight: "Multi-agent credit committee simulation with distinct personas (Risk Officer, Compliance, SME Specialist, Head of Credit) each providing independent recommendations.",
    simpleExplanation: "Every loan gets analyzed by 9 different AI engines. A simulated committee of AI experts reviews the case. Officers make the final call.",
    highlightSelector: "[class*='space-y']",
    icon: "briefcase",
  },
  {
    id: "production-memo",
    title: "Production Credit Memo",
    path: "/applications/[id]/production-memo",
    purpose: "Bank-grade credit memo with AI-generated summary, risk assessment, financial analysis, and recommendation for approval authorities.",
    businessValue: "Replaces manual memo writing that takes 3-4 hours per application with AI-generated comprehensive credit memo in seconds.",
    aiFeatures: ["AI-generated credit memo with structured sections", "Automated risk rating calculation", "Financial ratio analysis with peer comparison"],
    bankingWorkflow: ["View complete credit memo for approval", "Review risk assessment summary", "Inspect financial ratio analysis", "Final decision recording"],
    judgeObservations: ["Professional credit memo layout with bank branding", "Structured sections (summary, risk, financials, recommendation)", "Print-optimized formatting"],
    estimatedTime: "45 sec",
    relatedPages: [{ label: "Application Workspace", path: "/applications/app-1001" }, { label: "Timeline", path: "/applications/app-1001/timeline" }],
    recommendedNext: { label: "Customer 360", path: "/portfolio/MSME001?role=manager" },
    tourOrder: 8,
    whyJudgeCares: "AI-generated credit memos are the holy grail of banking — this replaces 3-4 hours of manual work with structured, bank-compliant output.",
    innovationHighlight: "Production-ready credit memo format with proper risk rating, financial ratios, and auditor notes — matches real bank memo standards.",
    simpleExplanation: "AI writes a complete credit memo that would normally take an analyst 3-4 hours. Ready for printing and signing.",
    highlightSelector: "main",
    icon: "fileText",
  },
  {
    id: "portfolio-msme",
    title: "Customer 360 / MSME Drilldown",
    path: "/portfolio/[msmeId]",
    purpose: "Deep-dive into a single MSME with full financial profile, risk analysis, relationship timeline, and document evidence.",
    businessValue: "Complete customer view enables relationship managers to make informed decisions with all data in one screen.",
    aiFeatures: ["Full AI intelligence on MSME financial health", "Historical risk band progression", "Document confidence summary"],
    bankingWorkflow: ["Review MSME financial profile", "Inspect relationship timeline", "View document evidence", "Analyze risk factors"],
    judgeObservations: ["Full-screen MSME profile layout", "Risk band progression timeline", "Financial signals visualization", "Relationship timeline integration"],
    estimatedTime: "45 sec",
    relatedPages: [{ label: "Portfolio", path: "/portfolio" }, { label: "Application Workspace", path: "/applications/app-1001" }],
    recommendedNext: { label: "Portfolio Intelligence", path: "/portfolio?role=manager" },
    tourOrder: 9,
    whyJudgeCares: "Shows complete customer data aggregation — financials, risk, documents, and timeline in one unified view.",
    innovationHighlight: "Risk band progression timeline shows how an MSME's risk profile evolved over months — predictive trend visualization.",
    simpleExplanation: "Everything about a business in one screen — their finances, risk score, documents, and full history with the bank.",
    highlightSelector: "main",
    icon: "users",
  },
  {
    id: "portfolio",
    title: "Portfolio Intelligence",
    path: "/portfolio",
    purpose: "Enterprise-grade portfolio monitoring with risk heatmaps, sector comparisons, exposure treemaps, and migration timelines.",
    businessValue: "Enables proactive risk management by identifying sector concentration, risk migration trends, and early warning patterns before losses materialize.",
    aiFeatures: ["AI-powered risk score aggregation across portfolio", "Automated early warning detection", "Dynamic credit limit recommendations per MSME", "Risk migration trend analysis over time"],
    bankingWorkflow: ["Monitor overall portfolio health score", "Analyze sector-wise risk distribution", "Track risk band migration month-over-month", "Review branch performance metrics", "Drill down into individual MSME profiles"],
    judgeObservations: ["Premium charts — donut, heatmap, treemap, bar comparison", "Risk migration timeline with animated transitions", "Branch performance cards with utilization metrics", "Sector comparison with risk distribution", "Dynamic credit limit delta indicators"],
    estimatedTime: "1 min",
    relatedPages: [{ label: "MSME Drilldown", path: "/portfolio/MSME001" }, { label: "Audit", path: "/audit" }],
    recommendedNext: { label: "Audit Trail", path: "/audit?role=manager" },
    tourOrder: 10,
    whyJudgeCares: "Enterprise-grade visualizations (heatmap, treemap, risk migration) that most production banking platforms don't have.",
    innovationHighlight: "Six different chart types on one page — donut, heatmap, treemap, bar, migration timeline, and branch comparison — all interactive.",
    simpleExplanation: "See your entire loan portfolio at a glance — which sectors are risky, which branches are performing, and where problems are emerging.",
    highlightSelector: "[class*='grid']",
    icon: "barChart",
  },
  {
    id: "audit",
    title: "Audit Center",
    path: "/audit",
    purpose: "Complete compliance audit trail with decision timestamps, AI rationale snapshots, role-based access logs, and exportable reports.",
    businessValue: "Regulatory compliance-ready audit logs that capture every decision with AI rationale, satisfying RBI and statutory audit requirements.",
    aiFeatures: ["AI rationale snapshot for every decision", "Confidence scoring in audit records", "Automated audit report generation"],
    bankingWorkflow: ["View complete audit event history", "Filter by date, user, action, and application", "Inspect AI rationale snapshots per decision", "Export audit reports for regulatory review"],
    judgeObservations: ["Structured audit table with filters", "AI rationale expansion per event", "Role-based access indicators", "Export functionality for compliance reporting"],
    estimatedTime: "45 sec",
    relatedPages: [{ label: "Reporting", path: "/reporting" }, { label: "Command Center", path: "/command-center" }],
    recommendedNext: { label: "Reporting Center", path: "/reporting?role=manager" },
    tourOrder: 11,
    whyJudgeCares: "Immutable audit logs with AI rationale snapshots are critical for RBI compliance — shows the system is bank-ready, not just a demo.",
    innovationHighlight: "AI rationale is frozen at decision time into audit logs — full explainability preserved for regulators even if models change later.",
    simpleExplanation: "Every decision is recorded with proof — who decided, what AI recommended, and why. Ready for any audit or regulator.",
    highlightSelector: "table",
    icon: "shield",
  },
  {
    id: "reporting",
    title: "Reporting Center",
    path: "/reporting",
    purpose: "Centralized reporting hub with portfolio summaries, risk reports, sector analysis, and lendable/managed report types.",
    businessValue: "Self-service reporting reduces analyst report generation time by 95% with pre-built templates and AI-generated insights.",
    aiFeatures: ["AI-generated report summaries", "Automated data aggregation across portfolio", "Intelligent report categorization"],
    bankingWorkflow: ["Browse available report types", "View report summaries and data", "Access detailed report views", "Executive dashboard for high-level oversight"],
    judgeObservations: ["Report cards with type badges (lendable/managed)", "Grid layout with report metadata", "Executive dashboard with portfolio KPIs", "Dynamic report detail views"],
    estimatedTime: "45 sec",
    relatedPages: [{ label: "Executive Dashboard", path: "/reporting/executive" }, { label: "Audit", path: "/audit" }],
    recommendedNext: { label: "Executive Dashboard", path: "/reporting/executive?role=manager" },
    tourOrder: 12,
    whyJudgeCares: "Self-service reporting with AI summaries shows the system is designed for real banking operations, not just demos.",
    innovationHighlight: "Reports categorized as 'lendable' (investor-ready) and 'managed' (internal) — matches real production banking report taxonomy.",
    simpleExplanation: "Find any report you need — portfolio summaries, risk reports, sector analysis. AI writes the executive summary.",
    highlightSelector: "[class*='grid']",
    icon: "fileText",
  },
  {
    id: "executive-dashboard",
    title: "Executive Dashboard",
    path: "/reporting/executive",
    purpose: "High-level executive overview with portfolio KPIs, risk distribution charts, sector analysis, and trend visualizations.",
    businessValue: "Board-ready dashboards that give executive leadership real-time visibility into portfolio health, risk exposure, and growth trends.",
    aiFeatures: ["AI-generated portfolio health summary", "Predictive risk trend indicators", "Automated KPI computation from live data"],
    bankingWorkflow: ["View portfolio-level KPIs", "Analyze risk distribution by sector", "Review exposure trends over time", "Monitor growth metrics"],
    judgeObservations: ["Premium line and bar charts with gradients", "KPI cards with CountUp animations", "Sector risk distribution visualization", "Trend analysis with confidence bands", "Board-presentation quality layout"],
    estimatedTime: "45 sec",
    relatedPages: [{ label: "Reporting", path: "/reporting" }, { label: "Portfolio", path: "/portfolio" }],
    recommendedNext: { label: "Portfolio Intelligence", path: "/portfolio?role=manager" },
    tourOrder: 13,
    whyJudgeCares: "Board-ready dashboards with premium charts — shows the system is designed for C-suite presentation, not just operational use.",
    innovationHighlight: "Premium Recharts integration with gradient fills, custom tooltips, and dynamic imports — same tech stack as production analytics tools.",
    simpleExplanation: "A boardroom-quality dashboard showing portfolio health, risk trends, and growth metrics — all updated in real-time.",
    highlightSelector: "[class*='grid']",
    icon: "trending",
  },
];

export function getGuide(pathname: string): GuideEntry | undefined {
  const normalized = pathname.split("?")[0];
  return GUIDES.find(
    (g) =>
      normalized === g.path ||
      (g.path.includes("[") && matchDynamicRoute(normalized, g.path))
  );
}

function matchDynamicRoute(path: string, pattern: string): boolean {
  const patternParts = pattern.split("/");
  const pathParts = path.split("/");
  if (patternParts.length !== pathParts.length) return false;
  return patternParts.every((p, i) => p.startsWith("[") || p === pathParts[i]);
}

export function getRecommendedNext(pathname: string): { label: string; path: string } | null {
  const guide = getGuide(pathname);
  return guide?.recommendedNext ?? null;
}

export const TOUR_STEPS: TourStep[] = [
  { pageId: "home", title: "Welcome to NexusNova", description: "An AI-powered MSME Lending Platform built for IDBI Innovate Hackathon. This landing page shows live portfolio metrics, role selection, and demo mode entry.", businessValue: "First impression matters — this page demonstrates the full platform breadth in under 30 seconds.", whyJudgeCares: "This page shows the depth and polish of the entire platform before you even log in.", innovationHighlight: "Real-time portfolio aggregation using pure in-memory computation — no backend required.", estimatedTime: "30 sec", simpleExplanation: "This is the front door. It shows live portfolio numbers, lets you pick a role, and seeds demo data with one click.", highlightSelector: "header", path: "/" },
  { pageId: "customer-dashboard", title: "Customer Dashboard", description: "360-degree customer view with active loan applications, document status, AI support, and dynamic loan recommendations.", businessValue: "Self-service portal reducing branch visits by 60% with real-time tracking and AI assistance.", whyJudgeCares: "Full customer self-service with AI chat — a key requirement for paperless banking innovation.", innovationHighlight: "BANK AI chatbot provides contextual support using pure TypeScript pattern matching — no external APIs.", estimatedTime: "45 sec", simpleExplanation: "Customers see everything about their loans, upload documents, and chat with AI support.", highlightSelector: "[class*='glass']", path: "/customer/dashboard" },
  { pageId: "customer-apply", title: "Loan Application", description: "Digital loan application with MSME registration, financial data entry, and AI-suggested loan products.", businessValue: "Paperless, branchless applications capturing regulatory data in under 3 minutes.", whyJudgeCares: "Complete digital onboarding flow — no paper, no branch visit, fully compliant.", innovationHighlight: "AI-suggested loan products adapt in real-time to the MSME profile entered.", estimatedTime: "30 sec", simpleExplanation: "A smart form that asks for business details and suggests the best loan product automatically.", highlightSelector: "form", path: "/customer/apply" },
  { pageId: "customer-documents", title: "Document Upload", description: "Upload GST returns, bank statements, ITRs, and KYC documents with AI-powered extraction and validation.", businessValue: "AI document intelligence reduces manual data entry by 80% with automatic extraction.", whyJudgeCares: "Document intelligence is the hardest AI problem in MSME lending — this shows automated extraction with confidence scoring.", innovationHighlight: "Simulated document AI that extracts GST, revenue, and bank data with per-field confidence — no external OCR needed.", estimatedTime: "30 sec", simpleExplanation: "Upload documents and AI reads them automatically — no manual data entry needed.", highlightSelector: "[class*='grid']", path: "/customer/documents" },
  { pageId: "customer-status", title: "Application Tracker", description: "Real-time tracking of all applications with status, SLA countdown, and AI readiness prediction.", businessValue: "Complete transparency with SLA tracking, reducing customer follow-up calls by 70%.", whyJudgeCares: "SLA tracking with AI readiness prediction shows practical banking workflow integration.", innovationHighlight: "AI readiness score predicts auto-approval potential before a human reviews the case.", estimatedTime: "30 sec", simpleExplanation: "See all applications in one place — what's approved, pending, and how long until a decision.", highlightSelector: "[class*='space-y']", path: "/customer/status" },
  { pageId: "command-center", title: "Command Center", description: "AI-powered operational hub with urgent cases, early warnings, portfolio exposure, and SLA monitoring.", businessValue: "Single-pane-of-glass monitoring reducing response time to critical events by 90%.", whyJudgeCares: "Where AI meets banking operations — early warnings, SLA tracking, and role-based views.", innovationHighlight: "Real-time early warning system detects MSME financial distress from revenue patterns.", estimatedTime: "45 sec", simpleExplanation: "A single dashboard where loan officers see urgent cases, portfolio alerts, and SLA deadlines.", highlightSelector: "[class*='grid']", path: "/command-center?role=loan-officer" },
  { pageId: "application-workspace", title: "Application Workspace", description: "Complete loan review with 9 AI engines, credit committee simulation, stress testing, and human decision workflow.", businessValue: "Reduces loan decision time from 5 days to under 2 hours with explainable AI recommendations.", whyJudgeCares: "The most feature-rich page — 9 AI engines, simulated committee, stress testing, and explainability.", innovationHighlight: "Multi-agent credit committee simulation with 4 distinct personas providing independent recommendations.", estimatedTime: "2 min", simpleExplanation: "Every loan gets analyzed by 9 different AI engines with a simulated committee review.", highlightSelector: "[class*='space-y']", path: "/applications/app-1001?role=loan-officer" },
  { pageId: "production-memo", title: "Production Credit Memo", description: "Bank-grade AI-generated credit memo with risk assessment, financial ratios, and auditor notes.", businessValue: "Replaces 3-4 hours of manual memo writing with structured, bank-compliant AI output.", whyJudgeCares: "AI-generated credit memos are the holy grail of banking — bank-ready, not just a demo.", innovationHighlight: "Matches real bank memo standards with proper risk ratings, financial ratios, and audit trail.", estimatedTime: "45 sec", simpleExplanation: "AI writes a complete credit memo ready for printing and signing in seconds.", highlightSelector: "main", path: "/applications/app-1001/production-memo?role=loan-officer" },
  { pageId: "portfolio-msme", title: "Customer 360", description: "Deep-dive into an MSME with full financial profile, risk analysis, documents, and relationship timeline.", businessValue: "Complete customer view enabling informed decisions with all data in one screen.", whyJudgeCares: "Complete customer data aggregation — financials, risk, documents, and timeline unified.", innovationHighlight: "Risk band progression timeline shows how risk profile evolved month-over-month.", estimatedTime: "45 sec", simpleExplanation: "Everything about a business — finances, risk, documents, and full history with the bank.", highlightSelector: "main", path: "/portfolio/MSME001?role=manager" },
  { pageId: "portfolio", title: "Portfolio Intelligence", description: "Enterprise portfolio monitoring with heatmaps, treemaps, migration timelines, and sector comparisons.", businessValue: "Proactive risk management identifying concentration, migration trends, and early warnings.", whyJudgeCares: "Enterprise-grade visualizations most production banking platforms don't have.", innovationHighlight: "Six chart types — donut, heatmap, treemap, bar, migration timeline, branch comparison.", estimatedTime: "1 min", simpleExplanation: "See your entire portfolio — risky sectors, branch performance, and emerging problems.", highlightSelector: "[class*='grid']", path: "/portfolio?role=manager" },
  { pageId: "audit", title: "Audit Trail", description: "Immutable audit logs with AI rationale snapshots, role-based access, and exportable compliance reports.", businessValue: "Regulatory compliance-ready logs satisfying RBI and statutory audit requirements.", whyJudgeCares: "Immutable audit logs with AI rationale — shows the system is bank-ready, not just a demo.", innovationHighlight: "AI rationale frozen at decision time — full explainability preserved for regulators.", estimatedTime: "45 sec", simpleExplanation: "Every decision recorded with proof — who decided, what AI said, and why. Ready for regulators.", highlightSelector: "table", path: "/audit?role=manager" },
  { pageId: "reporting", title: "Reporting Center", description: "Self-service reporting hub with portfolio summaries, risk reports, sector analysis, and AI summaries.", businessValue: "Reduces analyst report generation by 95% with pre-built templates.", whyJudgeCares: "Self-service reporting with AI summaries — designed for real banking operations.", innovationHighlight: "Reports categorized as lendable (investor-ready) and managed (internal) — matches production taxonomy.", estimatedTime: "45 sec", simpleExplanation: "Find any report — portfolio summaries, risk reports, sector analysis with AI summaries.", highlightSelector: "[class*='grid']", path: "/reporting?role=manager" },
  { pageId: "executive-dashboard", title: "Executive Dashboard", description: "Board-ready dashboard with portfolio KPIs, risk distribution, sector analysis, and trend visualizations.", businessValue: "Real-time executive visibility into portfolio health, risk exposure, and growth trends.", whyJudgeCares: "Board-ready dashboards with premium charts — designed for C-suite presentation.", innovationHighlight: "Premium Recharts with gradient fills, custom tooltips, and dynamic imports — same as production analytics.", estimatedTime: "45 sec", simpleExplanation: "A boardroom-quality dashboard showing portfolio health, risk trends, and growth metrics.", highlightSelector: "[class*='grid']", path: "/reporting/executive?role=manager" },
];

export const CHECKLIST: ChecklistItem[] = [
  { id: "home", label: "Welcome & Landing", path: "/" },
  { id: "customer-dashboard", label: "Customer Portal", path: "/customer/dashboard" },
  { id: "customer-apply", label: "Loan Application", path: "/customer/apply" },
  { id: "customer-documents", label: "Document Upload", path: "/customer/documents" },
  { id: "customer-status", label: "Application Status", path: "/customer/status" },
  { id: "command-center", label: "Command Center", path: "/command-center?role=loan-officer" },
  { id: "application-workspace", label: "AI Workspace", path: "/applications/app-1001?role=loan-officer" },
  { id: "production-memo", label: "Credit Memo", path: "/applications/app-1001/production-memo?role=loan-officer" },
  { id: "portfolio-msme", label: "Customer 360", path: "/portfolio/MSME001?role=manager" },
  { id: "portfolio", label: "Portfolio Intelligence", path: "/portfolio?role=manager" },
  { id: "audit", label: "Audit Trail", path: "/audit?role=manager" },
  { id: "reporting", label: "Reporting Center", path: "/reporting?role=manager" },
  { id: "executive-dashboard", label: "Executive Dashboard", path: "/reporting/executive?role=manager" },
];

export const AI_TOOLTIPS: Record<string, AiTooltipData> = {
  "financial-health": {
    label: "Financial Health Score",
    description: "AI evaluates the overall financial stability of a business by analyzing revenue trends, GST consistency, cash flow patterns, and debt levels.",
    dataSources: ["GST returns — tax filing consistency", "Bank statements — cash flow patterns", "Revenue trend — growth trajectory", "Debt-to-income ratio — existing obligations"],
    confidence: 96,
    businessMeaning: "Higher scores mean stronger financial health. Scores above 75 indicate low default risk. Scores below 50 require additional collateral.",
  },
  "repayment-risk": {
    label: "Repayment Risk",
    description: "AI predicts the likelihood of timely loan repayment based on historical transaction behavior and cash flow stability.",
    dataSources: ["EMI payment history — past repayment behavior", "Failed transactions — financial stress signals", "Cash flow volatility — income stability", "Revenue consistency — business predictability"],
    confidence: 94,
    businessMeaning: "Lower risk scores mean higher repayment confidence. Scores below 30 are high risk and may require additional guarantees.",
  },
  "fraud-risk": {
    label: "Fraud Risk Score",
    description: "AI detects potential fraud by analyzing document consistency, data anomalies, and unusual patterns in financial submissions.",
    dataSources: ["Document confidence scores — AI verification quality", "Data mismatch detection — inconsistencies across sources", "Tamper indicators — document alteration flags", "Concentration anomalies — unusual transaction patterns"],
    confidence: 92,
    businessMeaning: "Higher scores suggest higher fraud probability. Scores above 60 require enhanced due diligence before approval.",
  },
  "business-growth": {
    label: "Business Growth Forecast",
    description: "AI projects future business growth by analyzing revenue trends, GST filing history, and digital transaction growth.",
    dataSources: ["Revenue trend — historical growth rate", "GST filing consistency — compliance reliability", "UPI transaction growth — digital adoption", "Customer concentration — dependency risk"],
    confidence: 88,
    businessMeaning: "Positive forecast means expanding business. Used to determine loan tenure and eligibility for growth-linked loan products.",
  },
  "cash-flow": {
    label: "Cash Flow Stability",
    description: "AI assesses how consistently a business generates cash and whether it can comfortably cover existing loan obligations.",
    dataSources: ["Monthly inflow patterns — income seasonality", "Obligation coverage — ability to pay existing debts", "Revenue volatility — income fluctuation risk"],
    confidence: 91,
    businessMeaning: "Stable cash flow means reliable loan servicing. Volatility above 30% triggers additional financial scrutiny.",
  },
  "credit-limit": {
    label: "Dynamic Credit Limit",
    description: "AI computes the optimal loan amount a business can safely borrow based on financial capacity, risk profile, and existing debt.",
    dataSources: ["Average monthly revenue — repayment capacity", "Revenue volatility — risk buffer needed", "Customer concentration — diversification risk", "Existing obligations — current debt burden"],
    confidence: 93,
    businessMeaning: "The safe limit is the recommended loan amount. The max limit is the ceiling under current financials — exceeding it increases risk.",
  },
  "ai-readiness": {
    label: "AI Readiness Score",
    description: "AI determines whether an application has enough reliable data to be processed automatically or needs human review.",
    dataSources: ["Document completeness — all required docs uploaded", "Data confidence — AI trust level in extracted data", "Risk thresholds — score within acceptable ranges", "Fraud indicators — no suspicious patterns detected"],
    confidence: 95,
    businessMeaning: "AI-ready applications can be auto-approved. Manual review triggers when data quality or risk scores fall below thresholds.",
  },
  "portfolio-health": {
    label: "Portfolio Health Score",
    description: "AI aggregates the health of all MSME loans in the portfolio into a single score, highlighting overall risk exposure.",
    dataSources: ["Individual MSME health scores — per-business assessment", "Risk band distribution — portfolio risk composition", "Early warning density — emerging problem count", "Sector concentration — diversification quality"],
    confidence: 97,
    businessMeaning: "Scores above 80 = healthy portfolio. Scores below 60 = management attention required. Trend direction matters more than absolute score.",
  },
};

export const FEATURE_DISCOVERY = [
  { id: "production-memo", label: "Production Credit Memo", path: "/applications/app-1001/production-memo" },
  { id: "audit-center", label: "Audit Trail", path: "/audit" },
  { id: "executive-dashboard", label: "Executive Dashboard", path: "/reporting/executive" },
  { id: "stress-simulator", label: "Stress Simulator", path: "/applications/app-1001" },
  { id: "credit-committee", label: "AI Credit Committee", path: "/applications/app-1001" },
  { id: "customer-360", label: "Customer 360 View", path: "/portfolio/MSME001" },
];

export const TOTAL_TOUR_STEPS = TOUR_STEPS.length;
